name: 'Review Apps Environment'

trigger: none
pr: none


parameters:
  - name: PR_NUMBER
    displayName: PR Number
    type: string
  - name: SHA
    displayName: Commit SHA
    type: string
  - name: ACTION
    displayName: PR Action
    type: string

variables:
  DOCKER_REGISTRY: 'ghcr.io/josielbruk'
  FRONTEND_IMAGE: '$(DOCKER_REGISTRY)/$(Build.Repository.Name):pr-${{ parameters.PR_NUMBER }}-${{ parameters.SHA }}'
  AZURE_CONTAINERAPPS_ENV: 'cae-review-apps-env'
  AZURE_RESOURCE_GROUP: 'rg-cae-review-apps'
  DB_NAME: 'reviewapp'
  DB_USER: 'reviewuser'
  DB_PASSWORD: 'reviewpassword'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Deploy
  condition: or(eq('${{ parameters.ACTION }}', 'opened'), eq('${{ parameters.ACTION }}', 'synchronize'), eq('${{ parameters.ACTION }}', 'reopened'), eq('${{ parameters.ACTION }}', 'modified'))
  jobs:
  - job: DeployReviewApp
    steps:
    - checkout: self

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'az-ado-sc'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        name: Deploy Review App
        inlineScript: |
          # Deploy the Postgres container app first
          az containerapp create \
            --name db-pr-${{ parameters.PR_NUMBER }} \
            --resource-group $(AZURE_RESOURCE_GROUP) \
            --environment $(AZURE_CONTAINERAPPS_ENV) \
            --image postgres:16-alpine \
            --min-replicas 1 \
            --max-replicas 5 \
            --env-vars POSTGRES_DB=$(DB_NAME) POSTGRES_USER=$(DB_USER) POSTGRES_PASSWORD=$(DB_PASSWORD) \
            --ingress internal \
            --target-port 5432 \
            --transport 'tcp'

          # Retrieve the FQDN of the Postgres container app
          DB_FQDN=$(az containerapp show \
            --name db-pr-${{ parameters.PR_NUMBER }} \
            --resource-group $(AZURE_RESOURCE_GROUP) \
            --query properties.configuration.ingress.fqdn -o tsv)
          DB_FQDN=${DB_FQDN//\"/}

          # Deploy the frontend container app with the correct DB_HOST
          az containerapp create \
            --name frontend-pr-${{ parameters.PR_NUMBER }} \
            --resource-group $(AZURE_RESOURCE_GROUP) \
            --environment $(AZURE_CONTAINERAPPS_ENV) \
            --image $(FRONTEND_IMAGE) \
            --ingress external \
            --target-port 443 \
            --env-vars DB_HOST=db-pr-${{ parameters.PR_NUMBER }} DB_PORT=5432 DB_NAME=$(DB_NAME) DB_USER=$(DB_USER) DB_PASSWORD=$(DB_PASSWORD) \
            --query properties.configuration.ingress.fqdn

- stage: Cleanup
  condition: eq('${{ parameters.ACTION }}', 'closed')
  jobs:
  - job: CleanupReviewApp
    steps:
    - checkout: self

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'az-ado-sc'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        name: Cleanup Review App
        inlineScript: |
          az containerapp delete --name frontend-pr-${{parameters.PR_NUMBER }} --resource-group $(AZURE_RESOURCE_GROUP) --yes
          az containerapp delete --name db-pr-${{parameters.PR_NUMBER }} --resource-group $(AZURE_RESOURCE_GROUP) --yes
