name: 'Review App Build & Deploy Pipeline'

trigger: none
pr: none

variables:
  DOCKER_REGISTRY: 'ghcr.io/$(Build.Repository.Name)'
  DB_IMAGE: 'ghcr.io/$(Build.Repository.Name)/pr-$(PR_NUMBER)-db:$(SHA)'
  FRONTEND_IMAGE: 'ghcr.io/$(Build.Repository.Name)/pr-$(PR_NUMBER)-app:$(SHA)'
  AZURE_CONTAINERAPPS_ENV: 'cae-review-apps-env'
  AZURE_RESOURCE_GROUP: 'rg-cae-review-apps'
  DB_NAME: 'reviewapp'
  DB_USER: 'reviewuser'
  DB_PASSWORD: 'reviewpassword'


parameters:
  - name: PR_NUMBER
    displayName: PR Number
    type: string
  - name: SHA
    displayName: Commit SHA
    type: string

pool:
  vmImage: 'ubuntu-latest'

stages:

- stage: Deploy
  jobs:
  - job: DeployReviewApp
    steps:
    - checkout: self

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'az-ado-sc'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az containerapp create \
            --name frontend-pr-${{ parameters.PR_NUMBER }} \
            --resource-group $(AZURE_RESOURCE_GROUP) \
            --environment $(AZURE_CONTAINERAPPS_ENV) \
            --image $(FRONTEND_IMAGE) \
            --env-vars DB_HOST=db-pr-${{ parameters.PR_NUMBER }} DB_PORT=5432 DB_NAME=$(DB_NAME) DB_USER=$(DB_USER) DB_PASSWORD=$(DB_PASSWORD)

          az containerapp create \
            --name db-pr-${{ parameters.PR_NUMBER }} \
            --resource-group $(AZURE_RESOURCE_GROUP) \
            --environment $(AZURE_CONTAINERAPPS_ENV) \
            --image $(DB_IMAGE) \
            --env-vars POSTGRES_DB=$(DB_NAME) POSTGRES_USER=$(DB_USER) POSTGRES_PASSWORD=$(DB_PASSWORD)

- stage: Cleanup
  condition: or(eq(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.Reason'], 'PullRequestMerged'))
  jobs:
  - job: CleanupReviewApp
    steps:
    - checkout: self

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'az-ado-sc'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az containerapp delete --name frontend-pr-$(PR_NUMBER) --resource-group $(AZURE_RESOURCE_GROUP) --yes
          az containerapp delete --name db-pr-$(PR_NUMBER) --resource-group $(AZURE_RESOURCE_GROUP) --yes
