name: 'Review App Build & Deploy Pipeline'

trigger: none
pr: none


parameters:
  - name: PR_NUMBER
    displayName: PR Number
    type: string
  - name: SHA
    displayName: Commit SHA
    type: string
  - name: ACTION
    displayName: PR Action
    type: string

variables:
  DOCKER_REGISTRY: 'ghcr.io/josielbruk'
  DB_IMAGE: '$(DOCKER_REGISTRY)/pr-${{ parameters.PR_NUMBER }}-db:${{ parameters.SHA }}'
  FRONTEND_IMAGE: '$(DOCKER_REGISTRY)/pr-${{ parameters.PR_NUMBER }}-app:${{ parameters.SHA }}'
  AZURE_CONTAINERAPPS_ENV: 'cae-review-apps-env'
  AZURE_RESOURCE_GROUP: 'rg-cae-review-apps'
  DB_NAME: 'reviewapp'
  DB_USER: 'reviewuser'
  DB_PASSWORD: 'reviewpassword'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Deploy
  condition: or(eq('${{ parameters.ACTION }}', 'opened'), eq('${{ parameters.ACTION }}', 'synchronize'), eq('${{ parameters.ACTION }}', 'reopened'), eq('${{ parameters.ACTION }}', 'modified'))
  jobs:
  - job: DeployReviewApp
    steps:
    - checkout: self

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'az-ado-sc'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az containerapp create \
            --name frontend-pr-${{ parameters.PR_NUMBER }} \
            --resource-group $(AZURE_RESOURCE_GROUP) \
            --environment $(AZURE_CONTAINERAPPS_ENV) \
            --image $(FRONTEND_IMAGE) \
            --env-vars DB_HOST=db-pr-${{ parameters.PR_NUMBER }} DB_PORT=5432 DB_NAME=$(DB_NAME) DB_USER=$(DB_USER) DB_PASSWORD=$(DB_PASSWORD)

          az containerapp create \
            --name db-pr-${{ parameters.PR_NUMBER }} \
            --resource-group $(AZURE_RESOURCE_GROUP) \
            --environment $(AZURE_CONTAINERAPPS_ENV) \
            --image $(DB_IMAGE) \
            --env-vars POSTGRES_DB=$(DB_NAME) POSTGRES_USER=$(DB_USER) POSTGRES_PASSWORD=$(DB_PASSWORD)

- stage: Cleanup
  condition: eq('${{ parameters.ACTION }}', 'closed')
  jobs:
  - job: CleanupReviewApp
    steps:
    - checkout: self

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'az-ado-sc'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az containerapp delete --name frontend-pr-${{parameters.PR_NUMBER }} --resource-group $(AZURE_RESOURCE_GROUP) --yes
          az containerapp delete --name db-pr-${{parameters.PR_NUMBER }} --resource-group $(AZURE_RESOURCE_GROUP) --yes
