---
config:
  theme: redux-color
  look: handDrawn
---
sequenceDiagram
    participant Dev as Developer
    participant GHA as GitHub Actions <br/>(CI)
    participant ADO as Azure DevOps <br/>(CD)
    participant ACA as Azure Container Apps
    Dev->>GHA: 1. Pushes commit to PR
    GHA->>GHA: 2. Build & Push Image to GHCR
    GHA->>ADO: 3. Trigger CD Pipeline
    ADO->>ACA: 4. Deploy Multi-Container App<br/>(App + Postgres DB)
    ACA-->>GHA: 5. (via ADO) Post URL back to PR Comment or Slack channel
