version: '3.8'
services:
  db:
    build: ./database
    ports:
      - "5432:5432"
    env_file:
      - ./database/.env.db.template
  frontend:
    build: ./frontend
    ports:
      - "8000:8000"
    env_file:
      - ./frontend/.env.frontend.template
    depends_on:
      - db
