
name: 'Review App Build & Publish'
on:
  pull_request:
    types: [opened, synchronize, closed, reopened]

permissions:
  id-token: write
  contents: read
  packages: write
  attestations: write

jobs:

  build:
    name: 'Build'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    env:
      REGISTRY: ghcr.io/${{ github.repository_owner }}
      APP_IMAGE_NAME: pr-${{ github.event.pull_request.number }}-app
      DB_IMAGE_NAME: pr-${{ github.event.pull_request.number }}-db

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend image
        id: push_app
        uses: docker/build-push-action@v5
        with:
          context: apps/frontend
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.APP_IMAGE_NAME }}:${{ github.sha }}

      - name: Make ${{ env.APP_IMAGE_NAME }} package public
        run: |
          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/users/${{ github.repository_owner }}/packages/container/${{ env.APP_IMAGE_NAME }} \
            -d '{"visibility":"public"}'

      - name: Build and push database image
        id: push_db
        uses: docker/build-push-action@v5
        with:
          context: apps/database
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.DB_IMAGE_NAME }}:${{ github.sha }}
      - name: Output image tags
        run: |
          echo "Frontend image: ${{ env.REGISTRY }}/${{ env.APP_IMAGE_NAME }}:${{ github.sha }}"
          echo "Database image: ${{ env.REGISTRY }}/${{ env.DB_IMAGE_NAME }}:${{ github.sha }}"

      - name: Make ${{ env.DB_IMAGE_NAME }} package public
        run: |
          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/users/${{ github.repository_owner }}/packages/container/${{ env.DB_IMAGE_NAME }} \
            -d '{"visibility":"public"}'

      # - name: Generate artifact attestation for frontend
        # uses: actions/attest-build-provenance@v2
        # with:
        #   subject-name: ${{ env.REGISTRY }}/${{ env.APP_IMAGE_NAME }}
        #   subject-digest: ${{ steps.push_app.outputs.digest }}
        #   push-to-registry: true

      # - name: Generate artifact attestation for database
        # uses: actions/attest-build-provenance@v2
        # with:
        #   subject-name: ${{ env.REGISTRY }}/${{ env.DB_IMAGE_NAME }}
        #   subject-digest: ${{ steps.push_db.outputs.digest }}
        #   push-to-registry: true

  trigger-azure-pipeline:
    name: 'Trigger Azure Pipeline for PR'
    needs: build
    uses: ./.github/workflows/review-app-trigger-azure-pipeline.yml

