
name: Trigger Azure Pipeline for PR
on:
  workflow_call:

permissions:
  id-token: write
  contents: read
jobs:
  trigger-azure-pipeline:
    name: Deploy Review App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get PR number and SHA
        id: pr_info
        run: |
          echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          echo "SHA=${{ github.sha }}" >> $GITHUB_ENV
          echo "DOCKER_TAG=PR-${{ github.event.pull_request.number }}-${{ github.sha }}" >> $GITHUB_ENV
      - name: Output PR number and Docker tag
        run: |
          echo "PR Number: $PR_NUMBER"
          echo "Docker Image Tag: $DOCKER_TAG"
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


      - name: Trigger Azure DevOps Pipeline via Azure CLI
        run: |
          az pipelines run --organization ${{ secrets.AZURE_DEVOPS_PROJECT_URL }} \
            --project manage-test \
            --name 'Review App Trigger Pipeline' \
            --variables PR_NUMBER=${{ env.PR_NUMBER }} SHA=${{ env.SHA }} DOCKER_TAG=${{ env.DOCKER_TAG }}
