name: 'Review App Build & Publish'

on:
  pull_request:
    types: [opened, synchronize, closed, reopened]

permissions:
  id-token: write
  contents: read
  packages: write
  attestations: write

env:
  ORG_NAME: 'josielbruk'  # 🔁 Replace this with your actual GitHub org name

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    timeout-minutes: 3

    env:
      REGISTRY: ghcr.io/${{ github.repository_owner }}
      APP_IMAGE_NAME: pr-${{ github.event.pull_request.number }}-app
      DB_IMAGE_NAME: pr-${{ github.event.pull_request.number }}-db

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend image
        id: push_app
        uses: docker/build-push-action@v5
        with:
          context: apps/frontend
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.APP_IMAGE_NAME }}:${{ github.sha }}

      - name: Make frontend image public
        run: |
          curl -L -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GHCR_PAT }}" \
            https://api.github.com/orgs/${{ env.ORG_NAME }}/packages/container/${{ env.APP_IMAGE_NAME }}/visibility \
            -d '{"visibility":"public"}'

      - name: Build and push database image
        id: push_db
        uses: docker/build-push-action@v5
        with:
          context: apps/database
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.DB_IMAGE_NAME }}:${{ github.sha }}

      - name: Make database image public
        run: |
          curl -L -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GHCR_PAT }}" \
            https://api.github.com/orgs/${{ env.ORG_NAME }}/packages/container/${{ env.DB_IMAGE_NAME }}/visibility \
            -d '{"visibility":"public"}'

      - name: Output image tags
        run: |
          echo "Frontend image: ${{ env.REGISTRY }}/${{ env.APP_IMAGE_NAME }}:${{ github.sha }}"
          echo "Database image: ${{ env.REGISTRY }}/${{ env.DB_IMAGE_NAME }}:${{ github.sha }}"

  trigger-azure-pipeline:
    name: 'Trigger Azure Pipeline for PR'
    needs: build
    uses: ./.github/workflows/review-app-trigger-azure-pipeline.yml
